#!/bin/bash
#ddev-generated
## Description: Run axe_a11y checker
## Usage: axe_a11y [args]
## Example: "ddev axe_a11y https://www.example.be/"
## ExecRaw: true

output=$(docker exec ddev-${DDEV_PROJECT}-axe-a11y node axe.js "$@")
SUBSTRING=`echo $output | cut -d "@" -f2 | cut -d "@" -f1`

case $OSTYPE in
  linux-gnu)
    xdg-open ${DDEV_APPROOT}/.ddev/axe_a11y/${SUBSTRING}
    ;;
  "darwin"*)
    open ${DDEV_APPROOT}/.ddev/axe_a11y/${SUBSTRING}
    ;;
  "win*"* | "msys"*)
    start ${DDEV_APPROOT}/.ddev/axe_a11y/${SUBSTRING}
    ;;
esac
