#!/bin/bash
#ddev-generated
## Description: Run axe_a11y checker
## Usage: axe_a11y [args]
## Example: "ddev axe_a11y https://www.example.be/"
## ExecRaw: true

output=$(docker exec ddev-${DDEV_PROJECT}-axe-a11y node axe.js "$@")
SUBSTRING=`echo $output | cut -d "@" -f2 | cut -d "@" -f1`

case $OSTYPE in
  linux-gnu)
    if [ -n "$WSL_DISTRO_NAME" ]; then
      explorer.exe "$(wslpath -w $PWD/reports/axe_a11y/results/${SUBSTRING})"
    else
      xdg-open ${DDEV_APPROOT}/reports/axe_a11y/results/${SUBSTRING}
    fi
    ;;
  "darwin"*)
    open ${DDEV_APPROOT}/.ddev/axe_a11y/results/${SUBSTRING}
    ;;
  "win*"* | "msys"*)
    start ${DDEV_APPROOT}/.ddev/axe_a11y/results/${SUBSTRING}
    ;;
esac
